
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admingodoy-online
    ports:
      - "3306:3306"
    healthcheck: # Añade esto para que el backend espere a que la DB esté lista
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./admingodoy-online.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
  backend:
    build: ./backend
    container_name: nest_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run start:dev

  frontend:
    build: ./frontend
    container_name: next_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- -H 0.0.0.0

volumes:
  mysql_data: