FROM node:20-alpine

# bash/libstdc++ required for VS Code Server (Dev Containers attach) to run inside this Alpine image
RUN apk add --no-cache bash libstdc++ libgcc ca-certificates

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Prisma
RUN npx prisma generate

# Build Nest
RUN npm run build

EXPOSE 3000

CMD ["node", "dist/main"]